### ISSUE TITLE
ZT not exiting cleanly in WSL 2 terminal.

### ISSUE THREAD

**Issue by srdeotarse** [zulip/zulip-terminal#1193] opened 2022-04-10 12:11 UTC
After again running ``zulip-term -t gruvbox_dark -d`` - (debug mode)
After pressing ``ctrl``+``c`` to exit ZT, the ZT screen remains as it is without exiting cleanly as shown below -

![image](https://user-images.githubusercontent.com/53873549/162617112-35efdff6-139c-4260-8f72-22c5c6799fea.png)

After again running ``zulip-term -t gruvbox_dark -d`` command terminal display visible like this -

![image](https://user-images.githubusercontent.com/53873549/162617285-6d1bb782-8135-4e93-9b9a-0b7d8532f388.png)

After again running ``zulip-term`` - (normal mode) and pressing ``ctrl``+``c`` to exit ZT -

![image](https://user-images.githubusercontent.com/53873549/162617361-6a9ee71f-0958-41c5-bf67-4a6a8c639c88.png)

After again running ``zulip-term`` - 

![image](https://user-images.githubusercontent.com/53873549/162617399-df688e23-474d-460b-a720-931c46bab723.png)

**Comment by neiljp** [comment] 2022-04-11 00:05
@srdeotarse This seems to be a duplicate of #T1152, which as per there is maybe related to urwid/urwid#396.

**Comment by prah23** [comment] 2022-04-11 05:34
This might be a WSL specific issue with respect to rendering; the bare WSL application has this issue with rendering `zulip-term` and `zulip-term-check-symbols`. If you try it out on the Windows Terminal application, you'll notice a slightly different rendering issue when you exit. It might be a rendering issue with Windows terminal emulators.

**Comment by srdeotarse** [comment] 2022-04-11 05:41
@neiljp Yes this issue is mentioned in #T1152, should I close this issue?

**Comment by neiljp** [comment] 2022-04-11 23:11
@srdeotarse Yes, I'll close this in favor of the other issue for now, though the other issue author may have more thoughts.

**Closed by neiljp** 2022-04-11 23:11 UTC
