### ISSUE TITLE
Composing message when focus is on side-panel leaves it open in `--autohide` mode

### ISSUE THREAD

**Issue by zee-bit** [zulip/zulip-terminal#1042] opened 2021-05-29 22:33 UTC
Composing a message using `x` or `c` when the focus is on either of the side-panels, leaves it open when `--autohide` is specified as a command-line arg. A similar case happens when opening a draft with either of the side-panels open, which is discussed briefly in **#zulip-terminal>Bug: Drafts focus**.

This can lead to some easily reproducible cases where both the side-panels are open, which seems a bit strange for `--autohide`. We would like to have a general approach that can handle these corner-cases(and probably other similar cases) gracefully.

**Comment by neiljp** [comment] 2024-04-26 18:01
I can't reproduce this on `main`, and it looks like this was fixed in c96931a8c in #1100 (August 2021), so closing this now.

**Closed by neiljp** 2024-04-26 18:01 UTC
Labels: bug
