### ISSUE TITLE
Create additional (or update existing) themes

### ISSUE THREAD

**Issue by amanagr** [zulip/zulip-terminal#6] opened 2018-02-28 09:49 UTC
Simply add your theme to ui.pallete to create a new theme.
Previously added themes have become obsolete and they need to be updated. The `default` theme could also be improved.

**Comment by DhruvThakker** [comment] 2018-03-01 18:10
I would like to work on this issue

**Comment by amanagr** [comment] 2018-03-03 16:44
The mechanism for adding using new themes has been added, we can always create a new set palette for adding a theme.

**Comment by reshusinghhh** [comment] 2018-05-22 13:00
I would like to work on it too. 
Can anyone plz provide the communication channel for Zulip related queries??

**Comment by rht** [comment] 2018-12-15 02:46
I suppose adding major modern text editors colorscheme would be a start, e.g. onedark[1], gruvbox[2], or classic solarized.

[1] https://github.com/odedlaz/tmux-onedark-theme (https://github.com/joshdick/onedark.vim in vim)
[2] https://github.com/egel/tmux-gruvbox

**Comment by amanagr** [comment] 2018-12-16 05:00
Great idea @rht

**Comment by neiljp** [comment] 2019-01-09 21:23
We now have sufficient themes to be going with; the issue is existing themes being out of date.

I have a branch which makes this clearer for end-users and in testing, to show which themes are good or may be incomplete.

Should we close this and add a new issue for updating existing themes?

**Comment by timabbott** [comment] 2019-01-09 21:47
Yeah, that seems reasonable.

**Comment by neiljp** [comment] 2019-01-09 23:56
OK, I'll do that once that branch is merged, so we can refer to it.

**Comment by neiljp** [comment] 2019-01-13 19:51
With the merging of #251, which enables CI & run-time feedback of theme completeness, I'm closing this as discussed above, and will open another issue for updating/improving existing themes.

**Closed by neiljp** 2019-01-13 19:51 UTC
Labels: UI, difficult, help wanted
