### ISSUE TITLE
Multiple Servers

### ISSUE THREAD

**Issue by olynch** [zulip/zulip-terminal#726] opened 2020-07-18 16:59 UTC
Is it possible to connect to multiple servers with zulip-term? When I open two zulip-terms, the second one crashes.

**Comment by preetmishra** [comment] 2020-07-18 17:24
@olynch Thanks for reaching out. Could you post the traceback or elaborate on the crash?

The traceback should be in `zulip-terminal-tracebacks.log`.

**Comment by neiljp** [comment] 2020-07-18 20:50
@olynch Connecting to multiple servers should be entirely possible by running `zulip-term` in different terminals, though for each server/user to have its own parameters you'll need the `-c` or `--config-file` option - but I imagine you're using that? Was that clear?

For the one that is failing, can you reproduce this without running the other?

Which version are you running? We have recently fixed some bugs since 0.5.1 and are planning to release a  0.5.2 (to PyPI) relatively soon, though the fixes will be in git already.

**Comment by neiljp** [comment] 2020-08-30 18:13
@olynch Could you please let  us know if you are still experiencing this issue? Version 0.5.2 has been released, and 0.5.3 should be released relatively soon.

**Comment by neiljp** [comment] 2021-04-05 18:03
@olynch I'm closing this since we've not heard back from you for further information. Please reopen if you have more information for us or can reproduce this problem!

For reference you may be interested in:
* FAQ entry here: https://github.com/zulip/zulip-terminal/blob/main/docs/FAQ.md#how-do-i-access-multiple-servers
* a future aim, #961

**Closed by neiljp** 2021-04-05 18:03 UTC
Labels: issue requires user response
