### ISSUE TITLE
Bug: Dismantling of users list

### ISSUE THREAD

**Issue by SGeetansh** [zulip/zulip-terminal#522] opened 2020-03-05 19:11 UTC
It has been commonly observed that due to the rendering of emojis, the user list breaks. 

![bug1](https://user-images.githubusercontent.com/43946936/76015942-0388d200-5f42-11ea-8390-8270b2547584.jpeg)

The screenshots attached below indicate the instances when the list breaks even in the absence of emojis.

![bug2](https://user-images.githubusercontent.com/43946936/76016172-5ebac480-5f42-11ea-9d56-fe4a40d5260c.jpeg)

![bug3](https://user-images.githubusercontent.com/43946936/76016179-65493c00-5f42-11ea-8869-71941bac5e74.jpeg)

![bug4](https://user-images.githubusercontent.com/43946936/76187967-dd428b00-61fc-11ea-8816-dfc0fa6706b6.jpeg)

**Comment by amanagr** [comment] 2020-03-06 14:21
@SGeetansh Thanks for opening this issue, this issue is known to us and appears to be a problem  in the urwid library in the way they render multi-space characters. However, we are converting emojis into text all the time. I don't know how that emoji was rendered but we will look into it.

**Comment by SGeetansh** [comment] 2020-03-06 16:51
> @SGeetansh Thanks for opening this issue, this issue is known to us and appears to be a problem in the urwid library in the way they render multi-space characters. However, we are converting emojis into text all the time. I don't know how that emoji was rendered but we will look into it.

@amanagr Is there an explanation for the second image?

**Comment by amanagr** [comment] 2020-03-07 02:12
Interestingly, it looks weird. I don't think it should have happened in that case.

**Comment by preetmishra** [comment] 2020-03-27 18:07
This is a duplicate of #333.

**Comment by preetmishra** [comment] 2020-04-14 06:52
@zulipbot add label "duplicate"

**Comment by preetmishra** [comment] 2020-04-14 06:52
@zulipbot add "duplicate"

**Comment by neiljp** [comment] 2021-01-01 03:54
Closing this in preference to the duplicate, though this does provide some good data :+1:

**Closed by neiljp** 2021-01-01 03:54 UTC
Labels: bug, duplicate, help wanted
